name: Test
on:
  - push
  - pull_request
jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        nim-version:
          - stable
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: ${{ matrix.nim-version }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: nimble test -y
